apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: myapp
spec:
  selector:
    matchLabels:
      env: production # this label and pod label should match
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: production # this label and replicaset label should match
    spec:
      containers:
      - name: nginx
        image: nginx