apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  type: NodePort
  selector:
    name: result-app-pod
    app: demo-voting-app