# k create secret generic db-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123
# k describe secrets
# k get secrets 

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-11T17:15:12Z"
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
  resourceVersion: "935"
  uid: deb8dfbc-d765-4165-b0c6-deed6afc0022
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
        name: db-secret


# Additional Resource
# Dive deep into the world of Kubernetes security with our comprehensive guide to Secret Store CSI Driver.

# https://www.youtube.com/watch?v=MTnQW9MxnRI