apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: production # this label and pod label should match
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: production # this label and replicaset label should match
    spec:
      containers:
      - name: nginx
        image: nginx